//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("PW3_20152C_TP2_TorneosModel", "FK_Equipo_Torneo", "Torneo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication_TP1.DataBase.Torneo), "Equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication_TP1.DataBase.Equipo), true)]
[assembly: EdmRelationshipAttribute("PW3_20152C_TP2_TorneosModel", "FK_Jugador_Equipo", "Equipo", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(WebApplication_TP1.DataBase.Equipo), "Jugador", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication_TP1.DataBase.Jugador), true)]

#endregion

namespace WebApplication_TP1.DataBase
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class PW3_20152C_TP2_TorneosEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new PW3_20152C_TP2_TorneosEntities object using the connection string found in the 'PW3_20152C_TP2_TorneosEntities' section of the application configuration file.
        /// </summary>
        public PW3_20152C_TP2_TorneosEntities() : base("name=PW3_20152C_TP2_TorneosEntities", "PW3_20152C_TP2_TorneosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PW3_20152C_TP2_TorneosEntities object.
        /// </summary>
        public PW3_20152C_TP2_TorneosEntities(string connectionString) : base(connectionString, "PW3_20152C_TP2_TorneosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new PW3_20152C_TP2_TorneosEntities object.
        /// </summary>
        public PW3_20152C_TP2_TorneosEntities(EntityConnection connection) : base(connection, "PW3_20152C_TP2_TorneosEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Contacto> Contacto
        {
            get
            {
                if ((_Contacto == null))
                {
                    _Contacto = base.CreateObjectSet<Contacto>("Contacto");
                }
                return _Contacto;
            }
        }
        private ObjectSet<Contacto> _Contacto;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Equipo> Equipo
        {
            get
            {
                if ((_Equipo == null))
                {
                    _Equipo = base.CreateObjectSet<Equipo>("Equipo");
                }
                return _Equipo;
            }
        }
        private ObjectSet<Equipo> _Equipo;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Jugador> Jugador
        {
            get
            {
                if ((_Jugador == null))
                {
                    _Jugador = base.CreateObjectSet<Jugador>("Jugador");
                }
                return _Jugador;
            }
        }
        private ObjectSet<Jugador> _Jugador;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Torneo> Torneo
        {
            get
            {
                if ((_Torneo == null))
                {
                    _Torneo = base.CreateObjectSet<Torneo>("Torneo");
                }
                return _Torneo;
            }
        }
        private ObjectSet<Torneo> _Torneo;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Contacto EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToContacto(Contacto contacto)
        {
            base.AddObject("Contacto", contacto);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Equipo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEquipo(Equipo equipo)
        {
            base.AddObject("Equipo", equipo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Jugador EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJugador(Jugador jugador)
        {
            base.AddObject("Jugador", jugador);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Torneo EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTorneo(Torneo torneo)
        {
            base.AddObject("Torneo", torneo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PW3_20152C_TP2_TorneosModel", Name="Contacto")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Contacto : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Contacto object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombreCompleto">Initial value of the NombreCompleto property.</param>
        /// <param name="email">Initial value of the Email property.</param>
        /// <param name="comentario">Initial value of the Comentario property.</param>
        public static Contacto CreateContacto(global::System.Int32 id, global::System.String nombreCompleto, global::System.String email, global::System.String comentario)
        {
            Contacto contacto = new Contacto();
            contacto.Id = id;
            contacto.NombreCompleto = nombreCompleto;
            contacto.Email = email;
            contacto.Comentario = comentario;
            return contacto;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NombreCompleto
        {
            get
            {
                return _NombreCompleto;
            }
            set
            {
                OnNombreCompletoChanging(value);
                ReportPropertyChanging("NombreCompleto");
                _NombreCompleto = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NombreCompleto");
                OnNombreCompletoChanged();
            }
        }
        private global::System.String _NombreCompleto;
        partial void OnNombreCompletoChanging(global::System.String value);
        partial void OnNombreCompletoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Email
        {
            get
            {
                return _Email;
            }
            set
            {
                OnEmailChanging(value);
                ReportPropertyChanging("Email");
                _Email = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Email");
                OnEmailChanged();
            }
        }
        private global::System.String _Email;
        partial void OnEmailChanging(global::System.String value);
        partial void OnEmailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Comentario
        {
            get
            {
                return _Comentario;
            }
            set
            {
                OnComentarioChanging(value);
                ReportPropertyChanging("Comentario");
                _Comentario = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Comentario");
                OnComentarioChanged();
            }
        }
        private global::System.String _Comentario;
        partial void OnComentarioChanging(global::System.String value);
        partial void OnComentarioChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PW3_20152C_TP2_TorneosModel", Name="Equipo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Equipo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Equipo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        public static Equipo CreateEquipo(global::System.Int32 id, global::System.String nombre)
        {
            Equipo equipo = new Equipo();
            equipo.Id = id;
            equipo.Nombre = nombre;
            return equipo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MontoAbonado
        {
            get
            {
                return _MontoAbonado;
            }
            set
            {
                OnMontoAbonadoChanging(value);
                ReportPropertyChanging("MontoAbonado");
                _MontoAbonado = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MontoAbonado");
                OnMontoAbonadoChanged();
            }
        }
        private Nullable<global::System.Int32> _MontoAbonado;
        partial void OnMontoAbonadoChanging(Nullable<global::System.Int32> value);
        partial void OnMontoAbonadoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> IdTorneo
        {
            get
            {
                return _IdTorneo;
            }
            set
            {
                OnIdTorneoChanging(value);
                ReportPropertyChanging("IdTorneo");
                _IdTorneo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdTorneo");
                OnIdTorneoChanged();
            }
        }
        private Nullable<global::System.Int32> _IdTorneo;
        partial void OnIdTorneoChanging(Nullable<global::System.Int32> value);
        partial void OnIdTorneoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3_20152C_TP2_TorneosModel", "FK_Equipo_Torneo", "Torneo")]
        public Torneo Torneo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Torneo>("PW3_20152C_TP2_TorneosModel.FK_Equipo_Torneo", "Torneo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Torneo>("PW3_20152C_TP2_TorneosModel.FK_Equipo_Torneo", "Torneo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Torneo> TorneoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Torneo>("PW3_20152C_TP2_TorneosModel.FK_Equipo_Torneo", "Torneo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Torneo>("PW3_20152C_TP2_TorneosModel.FK_Equipo_Torneo", "Torneo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3_20152C_TP2_TorneosModel", "FK_Jugador_Equipo", "Jugador")]
        public EntityCollection<Jugador> Jugador
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Jugador>("PW3_20152C_TP2_TorneosModel.FK_Jugador_Equipo", "Jugador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Jugador>("PW3_20152C_TP2_TorneosModel.FK_Jugador_Equipo", "Jugador", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PW3_20152C_TP2_TorneosModel", Name="Jugador")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Jugador : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Jugador object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="apellido">Initial value of the Apellido property.</param>
        /// <param name="idEquipo">Initial value of the IdEquipo property.</param>
        public static Jugador CreateJugador(global::System.Int32 id, global::System.String nombre, global::System.String apellido, global::System.Int32 idEquipo)
        {
            Jugador jugador = new Jugador();
            jugador.Id = id;
            jugador.Nombre = nombre;
            jugador.Apellido = apellido;
            jugador.IdEquipo = idEquipo;
            return jugador;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Edad
        {
            get
            {
                return _Edad;
            }
            set
            {
                OnEdadChanging(value);
                ReportPropertyChanging("Edad");
                _Edad = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Edad");
                OnEdadChanged();
            }
        }
        private Nullable<global::System.Int32> _Edad;
        partial void OnEdadChanging(Nullable<global::System.Int32> value);
        partial void OnEdadChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IdEquipo
        {
            get
            {
                return _IdEquipo;
            }
            set
            {
                OnIdEquipoChanging(value);
                ReportPropertyChanging("IdEquipo");
                _IdEquipo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IdEquipo");
                OnIdEquipoChanged();
            }
        }
        private global::System.Int32 _IdEquipo;
        partial void OnIdEquipoChanging(global::System.Int32 value);
        partial void OnIdEquipoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3_20152C_TP2_TorneosModel", "FK_Jugador_Equipo", "Equipo")]
        public Equipo Equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("PW3_20152C_TP2_TorneosModel.FK_Jugador_Equipo", "Equipo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("PW3_20152C_TP2_TorneosModel.FK_Jugador_Equipo", "Equipo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Equipo> EquipoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Equipo>("PW3_20152C_TP2_TorneosModel.FK_Jugador_Equipo", "Equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Equipo>("PW3_20152C_TP2_TorneosModel.FK_Jugador_Equipo", "Equipo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="PW3_20152C_TP2_TorneosModel", Name="Torneo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Torneo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Torneo object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="nombre">Initial value of the Nombre property.</param>
        /// <param name="activo">Initial value of the Activo property.</param>
        public static Torneo CreateTorneo(global::System.Int32 id, global::System.String nombre, global::System.Boolean activo)
        {
            Torneo torneo = new Torneo();
            torneo.Id = id;
            torneo.Nombre = nombre;
            torneo.Activo = activo;
            return torneo;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean Activo
        {
            get
            {
                return _Activo;
            }
            set
            {
                OnActivoChanging(value);
                ReportPropertyChanging("Activo");
                _Activo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Activo");
                OnActivoChanged();
            }
        }
        private global::System.Boolean _Activo;
        partial void OnActivoChanging(global::System.Boolean value);
        partial void OnActivoChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("PW3_20152C_TP2_TorneosModel", "FK_Equipo_Torneo", "Equipo")]
        public EntityCollection<Equipo> Equipo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Equipo>("PW3_20152C_TP2_TorneosModel.FK_Equipo_Torneo", "Equipo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Equipo>("PW3_20152C_TP2_TorneosModel.FK_Equipo_Torneo", "Equipo", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
