//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication_TP1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EquiposDTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class EquiposDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreEquipoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreTorneoField;
        
        private bool ActivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreEquipo {
            get {
                return this.NombreEquipoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreEquipoField, value) != true)) {
                    this.NombreEquipoField = value;
                    this.RaisePropertyChanged("NombreEquipo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NombreTorneo {
            get {
                return this.NombreTorneoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreTorneoField, value) != true)) {
                    this.NombreTorneoField = value;
                    this.RaisePropertyChanged("NombreTorneo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool Activo {
            get {
                return this.ActivoField;
            }
            set {
                if ((this.ActivoField.Equals(value) != true)) {
                    this.ActivoField = value;
                    this.RaisePropertyChanged("Activo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.servicioSoap")]
    public interface servicioSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ObtenerEquiposResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerEquipos", ReplyAction="*")]
        WebApplication_TP1.ServiceReference1.ObtenerEquiposResponse ObtenerEquipos(WebApplication_TP1.ServiceReference1.ObtenerEquiposRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEquiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEquipos", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication_TP1.ServiceReference1.ObtenerEquiposRequestBody Body;
        
        public ObtenerEquiposRequest() {
        }
        
        public ObtenerEquiposRequest(WebApplication_TP1.ServiceReference1.ObtenerEquiposRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerEquiposRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool incluirDeTorneosInactivos;
        
        public ObtenerEquiposRequestBody() {
        }
        
        public ObtenerEquiposRequestBody(bool incluirDeTorneosInactivos) {
            this.incluirDeTorneosInactivos = incluirDeTorneosInactivos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ObtenerEquiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ObtenerEquiposResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication_TP1.ServiceReference1.ObtenerEquiposResponseBody Body;
        
        public ObtenerEquiposResponse() {
        }
        
        public ObtenerEquiposResponse(WebApplication_TP1.ServiceReference1.ObtenerEquiposResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ObtenerEquiposResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication_TP1.ServiceReference1.EquiposDTO[] ObtenerEquiposResult;
        
        public ObtenerEquiposResponseBody() {
        }
        
        public ObtenerEquiposResponseBody(WebApplication_TP1.ServiceReference1.EquiposDTO[] ObtenerEquiposResult) {
            this.ObtenerEquiposResult = ObtenerEquiposResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface servicioSoapChannel : WebApplication_TP1.ServiceReference1.servicioSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class servicioSoapClient : System.ServiceModel.ClientBase<WebApplication_TP1.ServiceReference1.servicioSoap>, WebApplication_TP1.ServiceReference1.servicioSoap {
        
        public servicioSoapClient() {
        }
        
        public servicioSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public servicioSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public servicioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication_TP1.ServiceReference1.ObtenerEquiposResponse WebApplication_TP1.ServiceReference1.servicioSoap.ObtenerEquipos(WebApplication_TP1.ServiceReference1.ObtenerEquiposRequest request) {
            return base.Channel.ObtenerEquipos(request);
        }
        
        public WebApplication_TP1.ServiceReference1.EquiposDTO[] ObtenerEquipos(bool incluirDeTorneosInactivos) {
            WebApplication_TP1.ServiceReference1.ObtenerEquiposRequest inValue = new WebApplication_TP1.ServiceReference1.ObtenerEquiposRequest();
            inValue.Body = new WebApplication_TP1.ServiceReference1.ObtenerEquiposRequestBody();
            inValue.Body.incluirDeTorneosInactivos = incluirDeTorneosInactivos;
            WebApplication_TP1.ServiceReference1.ObtenerEquiposResponse retVal = ((WebApplication_TP1.ServiceReference1.servicioSoap)(this)).ObtenerEquipos(inValue);
            return retVal.Body.ObtenerEquiposResult;
        }
    }
}
